import type { Metadata } from "next";


// import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { theme } from "./theme/theme";
import { CssBaseline } from "@mui/material";
import Header from "@/components/ui/Header";
import StoreProvider from "./StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        
      <body>


        <AppRouterCacheProvider >

          <ThemeProvider theme={theme}>

            <CssBaseline />
            <Header/>
            {/* {header} */}
            {/* {auth_modal} */}
            {children}

          </ThemeProvider>
        </AppRouterCacheProvider>


      </body>
      </StoreProvider>

    </html>
  );
}
