import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "@/components/ThemeRegistry";
import Header from "@/components/ui/Header/Header";
// import { store } from "@/store/store";
import { Provider } from "react-redux";
import { StoreProvider } from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <StoreProvider>
      <ThemeRegistry>
        <body className={inter.className}>
          <Header/>
          {children}
        </body>
        
      </ThemeRegistry>
      </StoreProvider>
    </html>
  );
}
